# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.

def findTheDifference1(s: str, t: str) -> str:
    OurDict = {}
    for char in s:
        OurDict[char] = OurDict.get(char, 0) + 1
    for char in t:
        if char in OurDict:
            if OurDict[char] > 1:
                OurDict[char] -= 1
            else:
                del OurDict[char]
        else:
            return char


def findTheDifference2(s: str, t: str) -> str: #не знаю как работает, что-то по битовому делает
    r = 0
    t = t+s
    for i in t:
        print(r)
        print(i)
        print(ord(i))
        r = r ^ ord(i)
    return chr(r)



s = "abcd"; t = "abcde"
print(findTheDifference2(s, t))